#!/bin/bash
sudo docker kill `sudo docker ps -q`
sudo docker kill `sudo docker ps -q`
sudo docker rm `sudo docker ps -aq`
sudo docker rm -f `sudo docker ps -aq`
sudo docker rm -f `sudo docker ps -aq`
sudo docker rmi `sudo docker images -q`
sudo docker rmi -f `sudo docker images -q`
sudo docker rmi -f `sudo docker images -q`
cd /runnable/node-hello-world
for CUR in 1 5 10 50 100; do
	echo "" > data
	echo "START P $CUR"	
	for i in `seq 1 $CUR`; do
	  ./load.sh &
	done

	for job in `jobs -p`; do
	  wait $job
	done
	cat data
done
