#!/bin/bash
cd /runnable/node-hello-world
./load.sh #do first pull
echo "" > data
for CUR in `seq 100 100 1000`; do
	echo "START p $CUR" >> data
	for i in `seq 1 $CUR`; do
	  ./load.sh &
	done

	for job in `jobs -p`; do
	  wait $job
	done
done
cat data
