#!/bin/bash
# ./series-test.sh <time log>
rm $1
./clean.sh > /dev/null
./runContainer.sh ../_tmp 
START="$(date +%s%N)"
for CUR in `seq 1 50`; do
  ./runContainer.sh $1
done
START="$(($(date +%s%N)-START))"
M="$((START/1000000))"
echo TOTAL TIME $M
echo AVG   TIME 
awk '{ sum += $1; n++} END { if (n > 0) print sum / n; }' $1
echo
