#!/bin/bash
# ./series-test.sh <time log>
echo "BUILD_TIME_MS,EXIT_CODE,TEST_TIME" > $1
./clean.sh
START="$(date +%s%N)"
for CUR in `seq 1 50`; do
  ./runContainer.sh
done
START="$(($(date +%s%N)-START))"
M="$((START/1000000))"
echo ",,$M" >> $1
cat $1
